# Generated by Django 4.2 on 2023-12-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='radius_in_km',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='district',
            name='user_color',
            field=models.CharField(default='#0000ff', max_length=10),
        ),
    ]
