# Generated by Django 4.2 on 2023-12-18 17:47

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="geolocation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=Point(0, 0), srid=4326
            ),
            preserve_default=False,
        ),
    ]
