# Generated by Django 4.2 on 2024-01-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_has_management_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_editing_staff_access',
            field=models.BooleanField(default=False),
        ),
    ]
