# Generated by Django 4.2 on 2024-02-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
